### ISSUE TITLE
Navigation bar improperly renders as the desktop version

### ISSUE THREAD

**Issue by rodrigoargumedo** [excid3/excid3.com#1]
See:

![screenshot_2015-09-15-08-27-38](https://cloud.githubusercontent.com/assets/7613139/9879351/41aa2e4c-5b84-11e5-9eaa-8e5a43124b87.png)

**Comment by excid3** [comment]
You caught me! I've done absolutely zero work on mobile design. I'm also not using any CSS frameworks, so I better write some mobile styles... :smile:

**Comment by rodrigoargumedo** [comment]
I might take care of the mobile styling and optimization. I will open a pull request when the opportunity is right. Keeping this open until resolved.

**Comment by rodrigoargumedo** [comment]
Oh, I fixed the site nav and made the links on hover prettier for you. Haha.
